# -*- coding: utf-8 -*-
"""SDS-CP028-smart-leaf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNuHcaODDgNoOWhnHrq1vSZOvgn2rQ8V

**Loading and Preprocessing Image Datasets with PyTorch**

Link to Dataset: https://www.kaggle.com/datasets/nafishamoin/new-bangladeshi-crop-disease

1. Install Libraries
"""

# !pip install torch
# !pip install torchvision
# !pip install numpy
# !pip install matplotlib

"""2. Importing libraries"""

# !pip install torchvision

import torch
import torchvision
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt
import numpy as np

"""3. **Loading the Dataset**

   We will use the torchvision.datasets.ImageFolder to load the dataset.
   
   **Generate a Kaggle API Key**
   Go to your Kaggle account settings: https://www.kaggle.com/account/account

   Scroll down to the "API" section.

   Click on "Create New API Token".

   This will download a file named kaggle.json containing your API key.
   Upload the Kaggle API Key to Google Colab                                                
   In your Google Colab notebook, create a new cell and run the following code
   to upload the kaggle.json file:                                                                        Click on "Choose Files" and select the kaggle.json file from your local machine.        

"""

from google.colab import drive
drive.mount("/content/drive")

from google.colab import files
files.upload()

"""       Move the API Key to the Correct Directory
       Run the following commands in a new cell to create the .kaggle directory and move the kaggle.json file to it:
       
"""

!mkdir -p ~/.kaggle
!mv kaggle2.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle2.json

"""      Download the Dataset
      
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("nafishamoin/new-bangladeshi-crop-disease")

print("Path to dataset files:", path)

!mkdir -p ./SDS-CP028
!mv /root/.cache/kagglehub/datasets/nafishamoin/new-bangladeshi-crop-disease/versions/2 ./SDS-CP028/



#data_dir_train = "drive/MyDrive/SDS-CP028/2/BangladeshiCrops/train"
#data_dir_test = "drive/MyDrive/SDS-CP028/2/BangladeshiCrops/test"

#local_dir_train = "BangladeshiCrops/train"
#local_dir_test = "BangladeshiCrops/test"

"""4. Preprocessing the Dataset

   Preprocessing is an essential step in preparing the data for training. Common preprocessing steps include resizing, normalization, and data augmentation.

  Define the transformations:
"""





"""5.  Creating Data Loaders
  Data loaders in PyTorch help in efficiently loading data during training.
  We will create a data loader for our training dataset.
"""



"""6. Visualizing the Data
Visualizing the data helps in understanding the dataset and verifying that the preprocessing steps are correctly applied.

"""



